### ISSUE TITLE
no exchange 'celeryresults' in vhost '/'

### ISSUE THREAD

**Issue by cybertk** [mher/node-celery#35]
When send jobs to a python worker, it failed with

```
{ [Error: NOT_FOUND - no exchange 'celeryresults' in vhost '/'] code: 404 }
```

**Comment by voltaicio** [comment]
I too was getting this message, and I think it occurs when you are attempting to send data back from the celery worker, without having first configured a result backend as specified here: http://celery.readthedocs.org/en/latest/getting-started/first-steps-with-celery.html#keeping-results

**Comment by mher** [comment]
thanks @voltaicio! Indeed, node-celery doesn't create the result exchange. You can launch celery worker before node-celery to ensure the result exchange is created.
