### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by asyncer** [mher/node-celery#39]
I've setup simple Celery worker but while the worker runs the task successfully I got error below on node-celery client,
Error: 
{ data: <Buffer 80 02 7d 71 01 28 55 06 73 74 61 74 75 73 71 02 55 07 53 55 43 43 45 53 53 71 03 55 09 74 72 61 63 65 62 61 63 6b 71 04 4e 55 06 72 65 73 75 6c 74 71 ... >,
  contentType: 'application/x-python-serialize' }
[TypeError: Cannot read property 'toLowerCase' of undefined]

My code:

var celery = require('node-celery'),
    client = celery.createClient({
        CELERY_BROKER_URL: 'amqp://guest:guest@localhost:5672//',
        CELERY_RESULT_BACKEND: 'amqp',
		CELERY_TASK_RESULT_EXPIRES : 3600
    });
var add = client.createTask('tests.tasks.add');

client.on('error', function(err) {
    console.log(err);
});

client.on('connect', function() {
    var result = add.call([1, 2]);
    result.on('ready', function(message) {
        console.log(message);
        client.end();
        client.broker.destroy();
    });
});

**Comment by mher** [comment]
node-celery only supports json serializer. Your tasks configuration should use

```
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
```

**Comment by mher** [comment]
No reply. Closing.
