### ISSUE TITLE
broker connection instantiate fails for amqps connections

### ISSUE THREAD

**Issue by shrinath-shenoy** [mher/node-celery#55]
The code here https://github.com/mher/node-celery/blob/1aedc6fe48e4e538f15df1f01076695013b6ec8b/celery.js#L121 decides the broker type based on the protocol present in uri. We can see that there is only amqp. Hence the amqps connections do not get instantiated and will throw exception here https://github.com/mher/node-celery/blob/1aedc6fe48e4e538f15df1f01076695013b6ec8b/celery.js#L177

**Comment by totopsy** [comment]
Resolved by the PR #63
