### ISSUE TITLE
Redis auth problem

### ISSUE THREAD

**Issue by hosseinko** [mher/node-celery#70]
I am using latest version and I have problem working with redis with password. The solution in issue [https://github.com/mher/node-celery/issues/18](url) is not working. I worked around the problem and came with a solution. In order to fix the issue you have to change celery.js as following

Line 137

self.redis = redis.createClient(purl.port, purl.hostname, {'auth_pass': purl.auth.split(':')[1]});

you have to add {'auth_pass': purl.auth.split(':')[1]}

**Comment by mher** [comment]
Fixed by #75
